apiVersion: apps/v1
kind: Deployment
metadata:
    name: apache
#    namespace: monitorado
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                #resources:
                #    requests:
                #        cpu: 100m
                #        memory: 100Mi
                - name: apache
                  image: httpd:latest
                  ports:
                    - containerPort: 80
                  #args:
                  #  - --kubelet-preferred-address-types=InternalIP
                  #  - --kubelet-insecure-tls