apiVersion: v1
kind: Service
metadata:
  name: apache-service
#  namespace: monitorado
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
  type: LoadBalancer
#  externalIPs:
#    - 192.168.100.6